/* ============================================================
   THE BASTION ARCHIVE — search index
   Add an entry here any time a new page is created.
   depth: 0 = root, 1 = one folder deep (characters/, locations/, world/)
   ============================================================ */
const BASTION_SEARCH_INDEX = [
  { title: "The Bastion Archive", type: "Home", url: "index.html", keywords: "home portal overview" },

  { title: "Scorio", type: "Character", url: "characters/scorio.html", keywords: "protagonist char cinder tomb spark blood baron the scourer red list proscribed house chimera withdrew renounced tournament heart fracture burn-off sol iron mana jova spike wager naomi rift praximar blackmail terrible idea nox delightful secret marinating imperial gel emberling kuragin duel eberro betrayal gauntlet second trial herdsmen infernarch fellowship departure left the academy" },
  { title: "Lianshi", type: "Character", url: "characters/lianshi.html", keywords: "cinder emberling pyre lord nun of the red journals academy juniper tutoring invulnerability immovability pledge reconciliation death cult acolyte funnel trap left the academy fellowship" },
  { title: "Leonis", type: "Character", url: "characters/leonis.html", keywords: "cinder emberling pyre lord golden king the grim academy kuragin pep talk tournament broken elbow old gauntlet pledge nezzar child king trial emberling final gauntlet run left the academy fellowship" },
  { title: "Naomi", type: "Character", url: "characters/naomi.html", keywords: "nightmare lady emberling widow's tower mistress esoka mentor readmitted feng kuragin tournament refusal rift the flame interlude estranged watching in secret alben worm rescue sapphire vials golden statuette left the academy fellowship" },
  { title: "Pyre Lord Praximar", type: "Character", url: "characters/praximar.html", keywords: "chancellor academy hydra hell whip antagonist other characters readmission final warning blackmail kayla heart oath sixth chamber public humiliation naomi readmission double defection" },
  { title: "Jova Spike", type: "Character", url: "characters/jova-spike.html", keywords: "tomb spark emberling imperator locker mystery juniper zala other characters ravenna accardi amber circuit wager sparring duel massamach heart oath nox journal warning herdsmen second place shroud tomb spark aura left the academy fellowship" },
  { title: "Imogen", type: "Character", url: "characters/imogen.html", keywords: "imperator antagonist portal ettera shadow fog mordecholio other characters the fallen lacuna sol zellair joranvyn house basilisk" },
  { title: "Dola", type: "Character", url: "characters/dola.html", keywords: "house basilisk narrows the double other characters kayla asking after" },
  { title: "Sol", type: "Character", url: "characters/sol.html", keywords: "imperator sol the just imogen husband ferula halo duplication scorio companion" },
  { title: "Other Characters", type: "Character Hub", url: "characters/other-characters.html", keywords: "minor characters feiyan helena radert helminth hell whip hera feng rex instructors jelan old memek havert hestia nissa salamander sal defenders praximar jova imogen dola ravenna accardi chen she exero famissa selena wrack gelegos house chimera recruiters chloe teleport kayla informant makiros unrest massamach ravenna accardi tomb spark chen she third place" },
  { title: "Kuragin", type: "Character", url: "characters/kuragin.html", keywords: "emberling top five rival crab claws carapace mess hall accusation duel eberro betrayal claim sir kuragin king's warmonger tournament winner jova spike team" },
  { title: "Juniper", type: "Character", url: "characters/juniper.html", keywords: "emberling fellowship jova spike roommate lianshi journals death cult acolyte reconciliation tutor left the academy" },
  { title: "Zala", type: "Character", url: "characters/zala.html", keywords: "emberling top five fellowship jova spike best friend roommate juniper left the academy" },
  { title: "Nox", type: "Character", url: "characters/nox.html", keywords: "imperial ghost toad old academy guardian burrow imperial gel delightful secret marinating technique quantics book favorite friend scorio leonis lianshi black star farm alben worm" },
  { title: "Nova", type: "Character", url: "characters/nova.html", keywords: "the white queen charnel duchess defenders of bastion imogen sol praximar readmission golden wings halo ferula fiery shoals empyreal prophecy watch list" },

  { title: "Book 1", type: "Story", url: "story/book-1.html", keywords: "summary plot chapters 1-80 complete story tournament house chimera sol praximar blackmail jova wager naomi rift lianshi emberling leonis elbow terrible idea marinating gambit nox gauntlet's end final gauntlet run departure fellowship herdsmen manticore infernarch open threads" },
  { title: "Book 2: Rascor Plains", type: "Story", url: "story/book-2.html", keywords: "book 2 rascor plains summary plot future unread fellowship manticore infernarch herdsmen teaser title reveal" },

  { title: "Bastion", type: "Location", url: "locations/bastion.html", keywords: "city cylinder sun-wire ruins narrows graveyard wards hell's door dead portal mutated architecture imogen aftermath deepening unrest makiros deniers" },
  { title: "The Academy", type: "Location", url: "locations/the-academy.html", keywords: "basilica archspire amber circuit hall of golden reflections mess hall tournament arena house sponsorship offices curriculum instructors library hexagonal cells parafiendology inimical botany banned histories warded books nox delightful secret marinating gelegos" },
  { title: "The Warrens", type: "Location", url: "locations/the-warrens.html", keywords: "final door brass door exile red list underground" },
  { title: "The Old Academy", type: "Location", url: "locations/the-old-academy.html", keywords: "abandoned ruins private gauntlet path of ascension archspire imogen" },

  { title: "Great Souls & Rank", type: "System", url: "world/great-souls.html", keywords: "path of ascension char cinder emberling tomb spark flame vault dread blaze pyre lord blood baron charnel duke crimson earl imperator archspire house sponsorship the fallen infernarch herdsmen warning journal scorio jova spike" },
  { title: "The Igneous Heart & Mana", type: "System", url: "world/igneous-heart.html", keywords: "mana coal copper iron bronze silver gold sapphire ruby diamond noumenon saturation tension ignition treasures fracturing burn-off the fallen lacuna four trials pill hierarchy black star fat cricket glittering sage luminous ghost peaceful wheel attenuation spider crystal gauge heart oath praximar blackmail jova spike wager delightful secret marinating technique imperial gel nox tomb spark condensation bronze mana" },
  { title: "The Gauntlet", type: "System", url: "world/the-gauntlet.html", keywords: "trial chambers old gauntlet private gauntlet trial room first trial four trials mandatory end of year run final run golden statuette funnel trap second trial tomb spark scorio jova spike chen she standings" },
  { title: "The Four Houses", type: "System", url: "world/the-houses.html", keywords: "hydra kraken chimera basilisk politics deniers empyreal prophecy sponsorship recruitment selena wrack gelegos" },
  { title: "The Empyreal Prophecy", type: "History", url: "world/empyreal-prophecy.html", keywords: "empyreal prophecy the pit ettera failed assault imogen sol zellair joranvyn the fallen house basilisk deniers riots unrest great soul organizations curriculum infernarch nova deep cut" },
  { title: "The Pit & Ettera", type: "Cosmology", url: "world/the-pit-and-ettera.html", keywords: "the pit ettera dead portal noumenon imperator the curse mana grade infernarch empyreal prophecy herdsmen scorio cosmology deep cut" },
];